Increase version number
Amsterdam/objectstore pull request #2
Opened 2020-09-07 08:22 UTC by JKoetsier

2020-09-07 08:34 UTC, jklardie requested changes
We should migrate towards semver version numbering, as it brings much more context to a version number than just a date.

https://semver.org/

2020-09-07 08:38 UTC, jklardie commented
This version is already available on pypi so the only thing we can do right now is merge this PR.

2020-09-07 08:39 UTC, jklardie approved these changes

2021-08-10 13:21 UTC, JKoetsier commented
@jklardie deze staat nog steeds open in m'n PR lijst. Maar mag 'm intussen niet meer mergen. Doe jij 'm nog even een zetje geven? ;)

2021-08-10 13:24 UTC, jklardie approved these changes

2021-09-30 10:37 UTC, closed without merging